[package]
name = "sway-utils"
version = "0.1.0"
authors = ["Caleb Bassi <calebjbassi@gmail.com>"]
edition = "2018"

[[bin]]
name = "sway-utils"
path = "src/main.rs"

[dependencies]
structopt = "0.2.15"
